# Generated by Django 5.2.10 on 2026-02-24 01:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="children",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
