# Generated by Django 5.2.10 on 2026-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "petid",
                    models.AutoField(
                        db_column="petID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("animaltype", models.CharField(db_column="animalType", max_length=5)),
                ("breed", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("availability", models.CharField(max_length=13)),
                ("datecreated", models.DateTimeField(db_column="dateCreated")),
                ("petphoto", models.CharField(db_column="petPhoto", max_length=500)),
                (
                    "newsitem",
                    models.TextField(blank=True, db_column="newsItem", null=True),
                ),
                ("goodwithchildren", models.IntegerField(db_column="goodWithChildren")),
                ("goodwithanimals", models.IntegerField(db_column="goodWithAnimals")),
                ("leashed", models.IntegerField()),
                ("energy", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "pets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="userID", primary_key=True, serialize=False
                    ),
                ),
                ("email", models.CharField(max_length=145, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=6)),
                ("datecreated", models.DateTimeField(db_column="dateCreated")),
                ("children", models.IntegerField(blank=True, null=True)),
                ("activity", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
